 
name: Linter

on:
  push:
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: File attributes Lint
        uses: yuk7/gh-action-attr-checker@main
      - name: Codes Lint
        run: |
          npm install
          npm run lint